# Use official Node.js image
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy package files to install dependencies

COPY ../server/package*.json ./

# Copy SSL certificates
COPY ../../ssl /app/ssl

# Install dependencies
RUN npm install

# Copy source code into container
COPY ../server ./

# Expose app port
EXPOSE 8444

CMD ["node", "server.js"]
