name: CI/CD for TaskSphere

on: 
  push:
    branches:
        - master  # or main, depending on your branch name

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: ${{ secrets.EC2_KEY}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f infra/docker/dockerfile -t tasksphere-backend .

      # Optional: Push Docker image to Docker Hub or GitHub Container Registry
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Push to Docker Hub
      #   run: docker push your-dockerhub-username/tasksphere-backend

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/TaskSphere
            git pull origin master
            docker-compose -f infra/docker-compose.yml down 
            docker-compose -f infra/docker-compose.yml up --build -d